[Settings]
# 开启浏览器运行，若更新无数据可开启此模式，较消耗性能; 可选值: True, False | Enable browser execution, If there are no updates, this mode can be enabled, which consumes more performance; Optional values: True, False
open_driver =True
# 开启无结果频道分类，自动归类至底部; 可选值: True, False | Enable empty category, automatically classified to the bottom; Optional values: True, False
open_empty_category = True
# 开启酒店源功能，关闭后所有酒店源工作模式都将关闭; 可选值: True, False | Enable hotel source function, after closing, all hotel source working modes will be closed; Optional values: True, False
open_hotel =True
# 开启 FOFA、ZoomEye 酒店源工作模式; 可选值: True, False | Enable FOFA, ZoomEye hotel source working mode; Optional values: True, False
open_hotel_fofa = True
# 开启代理，自动获取免费可用代理，若更新无数据可开启此模式; 可选值: True, False | Enable proxy, automatically obtain free available proxy, If there are no updates, this mode can be enabled; Optional values: True, False
open_proxy = True
# 接口协议类型偏好，优先将该类型的接口排在结果前面，可选值：ipv4、ipv6、自动、auto | Interface protocol type preference, prefer to put this type of interface in front of the result, optional values: ipv4, ipv6, 自动, auto
ipv_type_prefer = ipv4,ipv6
